### ISSUE TITLE
fc_quiver and phasing

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/FALCON_unzip#101]
Dear PacBio team,

I would like to test different alignment parameters with blasr and then polish my assembly directly with Quiver without using the fc_quiver.py script. But I have a question. 
My main goal is to keep the phase of my genome and I would like to know if the fc_quiver.py script participates in this step of phasing? Or only fc_unzip participates in this step of phasing ?

Thank you.
Best,
Amandine

**Comment by a-velt** [comment]
Dear PacBio team,

I don't know if someone has the answer of my question ?

Thank you very much.
Best,
Amandine

**Comment by mroach-awri** [comment]
I believe fc_unzip does the phasing, and unzip's quiver step will only map the phased reads. If you map your subreads to the diploid assembly (concatenated primary contigs and haplotigs) and polish then you should maintain the phasing.

**Comment by a-velt** [comment]
Thank you, this is what I did.

**Comment by mictadlo** [comment]
@a-velt Did it work for you to do it without `fc_quiver.py`?
