### ISSUE TITLE
LA4Falcon faild.

### ISSUE THREAD

**Issue by WenchaoLin** [PacificBiosciences/FALCON_unzip#105]
falcon_unzip faild, do you have any suggestions?

manually run `/3-unzip/reads/task.sh`  shows error as follows:

` LA4Falcon -m falcon/0-rawreads/raw_reads.db falcon/0-rawreads/m_00001/raw_reads.1.raw_reads.2.N0.las`

```
about to go into loop with novl = 166665 falcon/0-rawreads/m_00001/raw_reads.1.raw_reads.2.N0.las
before Read_Overlap record j = 0 out of 166665 at falcon/0-rawreads/m_00001/raw_reads.1.raw_reads.2.N0.las Thu Jan 11 11:21:09 2018
Segmentation fault (core dumped)
```

while I run the LA4Falcon executable copied from the origin FALCON bin with the same command  it shows:

```
LA4Falcon: Non-positive index?, '0'
```

**Comment by pb-cdunn** [comment]
Hmmm. If you could get a stack-trace for that LA4Falcon seg-fault, maybe we could help.

> while I run the LA4Falcon executable copied from the origin FALCON bin

I'm not sure what that means. Any idea which commit of DALIGNER is used for each?

**Comment by WenchaoLin** [comment]
The assembly were using  obsoleted falcon. Problem solved by update falcon to the latest version. Thanks.
