### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Wildish-LBL** [PacificBiosciences/FALCON_unzip#106]
Hi,

how do I install this from source? I can get as far as cloning the repository, running the setup.py script to build something, but then what? Do I have to set a bunch of environment variables (PATH, PYTHONPATH, whatever) or do I have to run something else to get the installation in the right place?

I'm stumped, and could use some help :-)

**Comment by pb-cdunn** [comment]
For now, your only real option is to download the binaries:
* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries
