### ISSUE TITLE
ngmlr instead of blasr

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON_unzip#109]
Hi,
is it possible to ngmlr rather than blasr?

Thank you in advance,

Michal

**Comment by pb-cdunn** [comment]
I'll bring this up at tomorrow's meeting. Blasr is used in 3 different places, and we might need different replacements. We're looking at minimap2 or DAMASKER for part of it.

**Comment by pb-cdunn** [comment]
Brought it up, but we're definitely going with minimap2 instead of ngmlr. Good discussion though.
