### ISSUE TITLE
SMRT Analysis v3.0

### ISSUE THREAD

**Issue by afinit** [PacificBiosciences/FALCON_unzip#11]
Jason et al
I saw another [issue](https://github.com/PacificBiosciences/FALCON_unzip/issues/7) about this but I didn't see an answer that would help me. It seems I need SMRT-Analysis v3.0 to begin working with FALCON_unzip. Could you guys point me to where I could download this? According to the release notes and installation notes on the [SMRT Analysis page here](http://www.pacb.com/products-and-services/analytical-software/smrt-analysis/), the latest release is v2.3.0. Are you guys referring to v2.3.0 as v3.0 for short?

I tried signing up for the Customer Portal to get tech support as suggested in the other issue, but I was not able to accomplish this. There was an error about not including the organization when I was signing up.

**Comment by peterdfields** [comment]
Is there an update on where smrtsuite 3.0 can be accessed?
