### ISSUE TITLE
Falcon outputs to Falcon_unzip

### ISSUE THREAD

**Issue by Jeff-Liu9453** [PacificBiosciences/FALCON_unzip#113]
Dear PacBio team,
I run Falcon and get aassembly genome with 548 contigs and I change some criteria of "run_falcon_asm.sh" then rerun it in 2-asm-falcon folder to get better assembly genome result(614contigs). Then I run falcon_unzip but result look like that falcon_unzip use old data from falcon because they only contain 540 contigs in  all_p_ctg.fa . I also found that in 3-unzip/reads/ctg_list only contain 548 contigs name. Is there a way to fix it? 
Thank you.
Best,
Jeff

**Comment by pb-cdunn** [comment]
You have to run unzip from a binary release. (And run falcon from the same binary, so you have consistent versions.)

* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries

**Comment by jasmynp** [comment]
Do you know what version of falcon is available in the binaries? Is it falcon/2.1.4?  

I'm testing it out and this is the first time I've seen it look for the directory 0-rawreads/las-gather.
