### ISSUE TITLE
wrong nucmer option in dedup_h_tigs.py

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/FALCON_unzip#121]
hasm.sh script failing at this point
```
#more script -- a little bit hacky here, we should improve
WD=$PWD
for f in `cat ../reads/ctg_list `; do mkdir -p $WD/$f; cd $WD/$f; python -m falcon_unzip.mains.dedup_h_tigs $f; done
#It is doing as below
nucmer -mum p_ctg.000000F.fa h_ctg_all.000000F.fa -p hp_aln
#but should be the with double dash as below which is why failing
nucmer --mum p_ctg.000000F.fa h_ctg_all.000000F.fa -p hp_aln
```
Where do I go to correct the script to add the extra "-" so it is "--mum" 

My version of fc_dedup_h_tigs.py has this in it
```
#!/usr/bin/env python2.7
# EASY-INSTALL-ENTRY-SCRIPT: 'falcon-unzip==0.4.0','console_scripts','fc_dedup_h_tigs.py'
__requires__ = 'falcon-unzip==0.4.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('falcon-unzip==0.4.0', 'console_scripts', 'fc_dedup_h_tigs.py')()
    )
```

I don't seem to have dedup_h_tigs.py in the bin folder of the precompiled binaries I am using but think I have found the script and made the change. Is this something that is known or somehow only me?

**Comment by rob123king** [comment]
I fixed this by providing a standalone script with the change and replacing it in the hasm.sh file so completed the hasm.sh script.

**Comment by pb-cdunn** [comment]
The latest binary release definitely uses `"nucmer --mum p_ctg.{ctg_id}.fa h_ctg_all.{ctg_id}.fa -p hp_aln"`. Glad you got your old version working though.

**Comment by rob123king** [comment]
that's good the binary release I had was only 2 and 1/2 months ago. not that old. It's taken me that long to get one complete run through working. thanks though

**Comment by pb-cdunn** [comment]
The releases are becoming more stable. There are just so many disparate pieces of software. Thanks for your patience.
