### ISSUE TITLE
FALCON_unzip run error, (fc_run:524 - INFO - Setup logging from file "None".)

### ISSUE THREAD

**Issue by whc2** [PacificBiosciences/FALCON_unzip#122]
Hello, everyone!

I'am running falcon pipeline on _E.coli_ genome. The falcon assembly is finished properly. p_ctg.fa only has one sequence 4,635,897bp and a_ctg.fa also has one sequence 30,013bp. After falcon assembly, I hope to run falcon_unzip process. However, an error occurs:
> 2018-05-16 15:40:59,496 - fc_run:524 - INFO - Setup logging from file "None".

I use the latest version of [falcon kits](https://downloads.pacbcloud.com/public/falcon/), *falcon-2018.05.04-19.00-py2.7-ucs2-beta.tar.gz*. And run falcon_unzip as such:
```
nohup fc_unzip.py fc_unzip_run_ecoli.cfg &
```
The **fc_unzip_run_ecoli.cfg** is learned from [falcon documentations](http://pb-falcon.readthedocs.io/en/latest/parameters.html) and  [Configuring-Unzip](https://github.com/PacificBiosciences/FALCON-integrate/wiki/Configuring-Unzip). 
My falcon_unzip config file:
```
[General]
#job_type = local
input_fofn = input.fofn
input_type = preads
length_cutoff = -1
genome_size = 4641652
seed_coverage = 30
length_cutoff_pr = 12000

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 6
overlap_filtering_setting = --max-diff 100 --max-cov 100 --min-cov 5 --bestn 10 --n-core 24

[Unzip]
input_fofn= input.fofn
#input_bam_fofn= input_bams.fofn
input_type = raw

smrt_bin = /vol1/software/pool/smrtlink/my_install/smrtcmds/bin/

sge_phasing= -pe smp 12
sge_quiver= -pe smp 24
sge_track_reads= -pe smp 12
sge_blasr_aln=  -pe smp 24
sge_hasm=  -pe smp 48
unzip_blasr_concurrent_jobs = 80
unzip_phasing_concurrent_jobs = 500
quiver_concurrent_jobs = 64

#
unzip_concurrent_jobs = 120
quiver_concurrent_jobs = 60

[job.defaults]
#job_type = SGE
job_type = local
#job_queue = all.q
NPROC=4
njobs=100
pwatcher_type = blocking
submit = /bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"
```
The command is run under the **same directory as falcon assembly**. And all falcon results are exist such as 0-rawreads, 1-preads_ovl, 2-asm-falcon _et. al._. It looks like **fc_unzip.py** doesn't recognize the falcon assembly. *I guess that the new version of falcon unzip needs some new parameters to be set and my config file is wrong.*
Here is nohup.out error:
```
falcon-unzip 1.1.1+git.eae3d7539d007377dd996dcf06b8953cdf0f3fe3
falcon-kit 1.2.0+git.0fcc93dc4f743af0cd27e7881546b768631b9b5b
pypeflow 2.0.2+git.cb894bb12a19eba6cdda2a2485bf8a5cbeadda9d
[INFO]Setup logging from file "None".
Traceback (most recent call last):
  File "/vol1/whc2/software/pool/Python-2.7.9/my_install/bin/fc_unzip.py", line 11, in <module>
    sys.exit(main())
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/start_unzip.py", line 29, in main
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/unzip.py", line 105, in run
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/unzip.py", line 69, in parse_config
AssertionError
```
I also test many times with different parameters, but none of them can run. I seek help to run smoothly falcon_unzip and will use falcon to assembly an agriculture pest genome.

Any suggestion or advice will be appreciated.
Thank you very much!

**Comment by pb-cdunn** [comment]
```
 68     assert 'input_bam_fofn' in config['Unzip']
```
Sorry. We should add some info to that assertion. Anyway, you are missing `input_bam_fofn`.

**Comment by whc2** [comment]
Thank your for your reply! Are bam files necessary to run **FALCON_Uzip**?

**Comment by pb-cdunn** [comment]
Yes, Unzip runs Quiver/ which needs BAM.
