### ISSUE TITLE
Unzip unfinished run (ask Node(3-unzip/2-htigs/chunk_000591F) failed with exit-code=256)

### ISSUE THREAD

**Issue by veronneaupy** [PacificBiosciences/FALCON_unzip#128]
Hi,

I tried to run unzip on my latest falcon assembly (12 SMRT cell of nematode ~120Mb genome) and it gets this error : 

_pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(3-unzip/2-htigs/chunk_000487F) failed with exit-code=256_

It then deletes all heartbeats files and stop.

here is the report for my input falcon assembly : 
_{
    "genome_length": 120000000,
    "length_cutoff": 4000,
    "preassembled_bases": 6640962036,
    "preassembled_coverage": 55.341,
    "preassembled_esize": 10469.713,
    "preassembled_mean": 6986.596,
    "preassembled_n50": 9607,
    "preassembled_p95": 16350,
    "preassembled_reads": 950529,
    "preassembled_seed_fragmentation": 1.465,
    "preassembled_seed_truncation": 1736.009,
    "preassembled_yield": 0.718,
    "raw_bases": 9611284160,
    "raw_coverage": 80.094,
    "raw_esize": 14299.757,
    "raw_mean": 10324.589,
    "raw_n50": 13193,
    "raw_p95": 22348,
    "raw_reads": 930912,
    "seed_bases": 9244328561,
    "seed_coverage": 77.036,
    "seed_esize": 14758.064,
    "seed_mean": 11952.704,
    "seed_n50": 13500,
    "seed_p95": 23261,
    "seed_reads": 773409
}_
Here is my fc_run.cfg : 
_[General]
input_fofn = input.fofn

input_type = raw

#openending = True

length_cutoff = 4000

genome_size = 120000000
seed_coverage = 60

length_cutoff_pr = 7000

sge_option_da = -pe smp 5 -q bigmem
sge_option_la = -pe smp 20 -q bigmem
sge_option_pda = -pe smp 6 -q bigmem 
sge_option_pla = -pe smp 16 -q bigmem
sge_option_fc = -pe smp 24 -q bigmem
sge_option_cns = -pe smp 12 -q bigmem

pa_concurrent_jobs = 50
cns_concurrent_jobs = 50
ovlp_concurrent_jobs = 50

pa_HPCdaligner_option =  -v -B128 -t16 -M24 -e.70 -l1000 -s400 -k14 -h80 -w8 
ovlp_HPCdaligner_option = -v -B128 -M24 -h100 -e.96 -l1000 -s400 -k14 

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -s400

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 2 --max_n_read 100 --n_core 50 
falcon_sense_skip_contained = False
overlap_filtering_setting = --max_diff 100 --max_cov 1000 --min_cov 2 --n_core 50_

And my fc_unzip.cfg: 
_[General]
job_type = local

[Unzip]
input_fofn= input.fofn
input_bam_fofn= input_bams.fofn

smrt_bin=/media/F/Falcon-Unzip-Juin2018/fc_env_180619/bin/

jobqueue =
sge_phasing=
sge_quiver=
sge_track_reads=
sge_blasr_aln=
sge_hasm=
unzip_concurrent_jobs = 50
quiver_concurrent_jobs = 50_

I read that exit-code=256 could mean a lack of memory but I check my system monitor and never got close to use all of my 512G of RAM...

Please guide thru this "not easy to understand" log and config files.

thank you very much,

PY

**Comment by ghannum** [comment]
I am having a very similar error.
Please see my issue post here: https://github.com/PacificBiosciences/FALCON/issues/652

**Comment by pb-cdunn** [comment]
We have fixed a lot of Unzip errors in the latest binary tarball. Please try that. If it fails again, we may ask for more details on the crash.
