### ISSUE TITLE
Issue with 4-quiver/merge-reads step

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [PacificBiosciences/FALCON_unzip#133]
Hi there,
I am running falcon-2018.07.25-07.01-py2.7-ucs${UCS_VER}-beta.tar.gz installed with the wrapper found here https://pb-falcon.readthedocs.io/en/latest/quick_start.html .

Falcon and unzip all work fine till the merge-reads step in quiver. 

When the pipeline tries to execute the following script it fails.

```
#!/bin/bash
printenv
echo
set -x
python2.7 -m pwatcher.mains.fs_heartbeat --directory=/home/smrtanalysis/benjaminS_analysis/Pst_104E_v2/FALCON_180725/run_1/4-quiver/merge-reads --heartbeat-file=/home/smrtanalysis/benjaminS_analysis/Pst_104E_v2/FALCON_180725/run_1/mypwatcher/heartbeats/heartbeat-Pfa7ea4563f981b --exit-file=/home/smrtanalysis/benjaminS_analysis/Pst_104E_v2/FALCON_180725/run_1/mypwatcher/exits/exit-Pfa7ea4563f981b --rate=10.0 /bin/bash run.sh || echo 99 >| /home/smrtanalysis/benjaminS_analysis/Pst_104E_v2/FALCON_180725/run_1/mypwatcher/exits/exit-Pfa7ea4563f981b
```
with exit code 256.

If I submit the same job manual with the full qsub command. The exit code is 0.

I am struggling to trouble shoot this any further at the moment as I cannot find the full error message anywhere.
The bam files with the reads were generated with bax2bam. The input_bam.fofn also contained the srcapps.bam. Might this have been the issue.

I am re-running the quiver step with the latest version of falcon falcon-2018.08.08-21.41-py2.7-ucs4-beta.tar.gz and without the scrapps.bams in the input_bam.fofn and got the same issue.

Any pointers what the issue could be would be greatly appreciated.

**Comment by BenjaminSchwessinger** [comment]
A bit off sleep fixed my issue. My input_bam.fofn also had the bam.bai files in them which generated an issue with this version of falcon unzip while previous version just handled this fine. So found the issue. Running now.

**Comment by pb-cdunn** [comment]
When there is a bad file in `input_bam.fofn`, should we raise an Exception or print a Warning?

**Comment by BenjaminSchwessinger** [comment]
I think this would be useful. Old versions of Falcon didn't care about this, hence I ran into this issue.

**Comment by pb-cdunn** [comment]
But which? An exception, or a warning? I'm not sure.

**Comment by BenjaminSchwessinger** [comment]
I would use an exception.
