### ISSUE TITLE
Arrow/variantCaller error

### ISSUE THREAD

**Issue by guilbar** [PacificBiosciences/FALCON_unzip#137]
Hi !

I'm currently using FALCON and FALCON_unzip locally. At the end, the fasta/fastq files of primary contigs and haplotigs are empty. I think that the error come from "variantCaller" but I don't know why it's not working. Here, you have an example for one contig but the same error occurred for all contigs/haplotigs.

```
set -vex
trap 'touch ../4-quiver/003196F/003196F_quiver_done.exit' EXIT
hostname
date

../pitchfork/bin/samtools faidx ../4-quiver/quiver_scatter/003196F/003196F_ref.fa
../pitchfork/bin/pbalign --tmpDir=/localdisk/scratch/ --nproc=10 --minAccuracy=0.75 --minLength=50          --minAnchorSize=12 --maxDivergence=30 --concordant --algorithm=blasr          --algorithmOptions=--useQuality --maxHits=1 --hitPolicy=random --seed=1            ../4-quiver/reads/003196F.bam ../4-quiver/quiver_scatter/003196F/003196F_ref.fa aln-003196F.bam
(../pitchfork/bin/variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 10 -r ../4-quiver/quiver_scatter/003196F/003196F_ref.fa aln-003196F.bam            -o ../4-quiver/003196F/cns-003196F.fasta.gz -o ../4-quiver/003196F/cns-003196F.fastq.gz) || echo quvier failed
date
touch ../4-quiver/003196F/003196F_quiver_done
```

And at the end of the file ../4-quiver/003196F/pwatcher.dir/stderr

> ../pitchfork/bin/samtools faidx ../4-quiver/quiver_scatter/003196F/003196F_ref.fa
> + ../pitchfork/bin/samtools faidx ../4-quiver/quiver_scatter/003196F/003196F_ref.fa
> ../pitchfork/bin/pbalign --tmpDir=/localdisk/scratch/ --nproc=10 --minAccuracy=0.75 --minLength=50          --minAnchorSize=12 --maxDivergence=30 --concordant --algorithm=blasr          --algorithmOptions=--useQuality --maxHits=1 --hitPolicy=random --seed=1            ../4-quiver/reads/003196F.bam ../4-quiver/quiver_scatter/003196F/003196F_ref.fa aln-003196F.bam
> + ../pitchfork/bin/pbalign --tmpDir=/localdisk/scratch/ --nproc=10 --minAccuracy=0.75 --minLength=50 --minAnchorSize=12 --maxDivergence=30 --concordant --algorithm=blasr --algorithmOptions=--useQuality --maxHits=1 --hitPolicy=random --seed=1 ../4-quiver/reads/003196F.bam ../4-quiver/quiver_scatter/003196F/003196F_ref.fa aln-003196F.bam
> (../pitchfork/bin/variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 10 -r ../4-quiver/quiver_scatter/003196F/003196F_ref.fa aln-003196F.bam            -o ../4-quiver/003196F/cns-003196F.fasta.gz -o ../4-quiver/003196F/cns-003196F.fastq.gz) || echo quvier failed
> + ../pitchfork/bin/variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 10 -r../4-quiver/quiver_scatter/003196F/003196F_ref.fa aln-003196F.bam -o ../4-quiver/003196F/cns-003196F.fasta.gz -o ../4-quiver/003196F/cns-003196F.fastq.gz
> Arrow: unsupported chemistries found: (unknown)
> + echo quvier failed

I already used FALCON and FALCON_unzip to assemble an other genome and nothing happened. If it can help, for the first genome (the one working correctly), i had bax files but for this one, i just have bam files :

> m54064_180605_121623.adapters.fasta  m54064_180605_121623.scraps.bam.pbi  m54064_180605_121623.subreads.bam.pbi  tmp-file-83b6b37a-6bc1-49b9-8264-3888c8690144.txt
> m54064_180605_121623.baz2bam_1.log   m54064_180605_121623.sts.xml         m54064_180605_121623.subreadset.xml
> m54064_180605_121623.scraps.bam      m54064_180605_121623.subreads.bam    m54064_180605_121623.transferdone
 
For the firsts steps of FALCON, I mad a bam2fasta conversion of the subreads.bam.

Thanks !

**Comment by gconcepcion** [comment]
It looks like you're using a version of variantCaller installed using pitchfork. What version variantCaller is it? You may need to update.

The version of variantCaller that we distribute with the current version of FALCON is 
```
$ source activate pb-assembly
(pb-assembly) $ variantCaller --version
2.3.2
```

**Comment by guilbar** [comment]
Hi @gconcepcion and thanks for your help !
My current version is 2.1.0 of variantCaller, but I'm not using the last version of FALCON. I will try to update and relaunch my assembly.

Have a good day!
