### ISSUE TITLE
please add /lib/libgcc_s.so.1 to prebuilt binaries or -static-libgcc

### ISSUE THREAD

**Issue by wangyugui** [PacificBiosciences/FALCON_unzip#138]
Hi,

Please add /lib/libgcc_s.so.1 to prebuilt binaries or -static-libgcc.

It will be more stable for prebuilt binaries .

Best Regards

**Comment by pb-cdunn** [comment]
That would be a good idea. However, we are switching to Bioconda. There might not be any other Binary releases. It's so much easier to let conda take care of dependencies.

**Comment by wangyugui** [comment]
@pb-cdunn 

Binary releases works well on my RHEL7.x with the help of python27-python-2.7.13;
please continue to provide it.

It is difficult to build it from the source on rhel7.x.

Best Regards

**Comment by wangyugui** [comment]
@pb-cdunn 

It will be difficult for conda  to provide better dependencies support than 'CentOS-7 - SCLo rh'?

Not only gcc/glibc/libstdc++/boost/hdf5, but also python2 2.7.13+/python2 package.

prebuilt binaries works on centos 7.x now. so please continue to provide it.

Best Regards

**Comment by pb-cdunn** [comment]
Though we will not delete what is already available, we just don't have time to maintain the binaries. It's really quite time-consuming, since it's completely separate from all other ways that we build.

I expect conda to work well for you in RHEL7.x. We might even add OSX support one of these days.

**Comment by wangyugui** [comment]
@pb-cdunn 

Yes, it need much time to maintain the binaries. but it need more time to build it from source for all the user too. and too many failure when building.

Porting is difficult for ptyhon than expected. virtualenv does work well as expected too.

maybe the binary release is the right way for big python applications such as 10xgenomics is doing.

Because the build/binary of FALCON is too difficult, only a few tuning job can be done by the user.
we need tuning the param by genome size, coverage, and others. but it is too difficult for the users to run it.

Best Regards.

**Comment by pb-cdunn** [comment]
Have you tried bioconda?

**Comment by wangyugui** [comment]
I have yet not tried bioconda.

dependencies is a general purpose problem, not a bio-spec problem.so I believe more in general purpose solution such as redhat scl. bioconda maybe works, but less user than general purpose redhat scl?

Best Regards
