### ISSUE TITLE
I couldn't fine mummer-3.3+

### ISSUE THREAD

**Issue by wyim-pgl** [PacificBiosciences/FALCON_unzip#139]
The most recent mummer-3 version  mummer-3.23.
mummer-3.3+ means mummer4 or mummer3.92?
Thanks!

**Comment by gconcepcion** [comment]
Either mummer 3.92 or mummer4 should work; but I advise you to use mummer4 going forward for the most up to date code
https://github.com/mummer4/mummer/releases

**Comment by wyim-pgl** [comment]
Great.
