### ISSUE TITLE
getting error "from: can't read /var/mail/qiime2.plugin"

### ISSUE THREAD

**Issue by srinivasanma** [PacificBiosciences/FALCON_unzip#142]
Hello,
      i am new to qiime platform, i installed the qiime2 while checking the plugins qiime2 types was missed and i tried to get the plugin by following code

**Artifact API Import**
                from qiime2.plugins import types
as per the link: https://docs.qiime2.org/2018.11/plugins/available/types/
 
![screenshot from 2019-01-06 17-42-15](https://user-images.githubusercontent.com/45750553/50735768-fb1bf680-11d9-11e9-9819-02992ea0bb65.png)

i got the error as : from: can't read /var/mail/qiime2.plugin

Kindly help me to fix the error

**Comment by pb-cdunn** [comment]
No idea. Please let us know if you find a solution or more details on the problem.
