### ISSUE TITLE
for a very long deletion like 10kb between alleles, which allele will be placed in the primary contig?

### ISSUE THREAD

**Issue by mapleforest** [PacificBiosciences/FALCON_unzip#144]
dear Author,

I like to ask if Falcon consistently select a longer or a shorter alleles into the primary contig.

For example, there is a 10kb deletion between two alleles, which allele would be retained in the primary contig?

best regards,
Shengfeng

**Comment by pb-cdunn** [comment]
Usually, the longer is in the "primary" contig, since that's the longest full path we can find. This is not configurable however.
