### ISSUE TITLE
Running FALCON and FALCON_UNZIP on different clusters

### ISSUE THREAD

**Issue by bostanict** [PacificBiosciences/FALCON_unzip#147]
Hi,

Due to some reasons I have run the falcon assembler on one cluster and got the results but I am not able to run the unzip on it on the same cluster. I want to know if I want to run the unzip on the assembled genome using another cluster, what folders and files I need on the destination machine to make it happen?

I know unzip uses a lot of pre-computed files etc. from falcon assembly step (https://github.com/PacificBiosciences/FALCON_unzip/issues/100), but since the files and directories generated are huge, and transferring them will take a long time and sometimes even not possible, I want to make sure what the essential files are and skip the others if possible.

Thanks for any guidance,

**Comment by pb-cdunn** [comment]
You need a lot of the `.las` files, which account of most of the disk-space, so basically you are best off just copying the entire tree to the other cluster.
