### ISSUE TITLE
raw sequence data fastq to sam

### ISSUE THREAD

**Issue by wj1106** [PacificBiosciences/FALCON_unzip#148]
Hi, I have a simple question.
I want to try Falon-unzip on my own data, but I only have raw fastq file. 
How can I convert it into bam file.
Thank you!

**Comment by pb-cdunn** [comment]
We don't support that yet.

**Comment by wj1106** [comment]
What a pity. 
Is this means I can't use falcon_unzip unless I have the raw fastq and bam file?

**Comment by pb-cdunn** [comment]
If you use a Sequel machine, you have a bam file.

**Comment by wj1106** [comment]
Right, unfortunately the company didn't give us bam file and it's been two years since we got the data.
Can I use samtools to convert fastq into bam file?

**Comment by pb-cdunn** [comment]
Not today, and though `.fq` may be possible someday, I couldn't estimate when. Sorry.

**Comment by wj1106** [comment]
Thanks for your patient!
