### ISSUE TITLE
[Error] Cannot run Falcon_unzip on greg200k-sv2 data set because of unsupported sequencing chemistry combination

### ISSUE THREAD

**Issue by AxelMacFoly** [PacificBiosciences/FALCON_unzip#153]
Hello,
I tried to run the example data set mentioned on the pb-assembly wiki page called "greg200k-sv2". Unfortunately the pipeline exits and the following error can be found within the  4-polish/quiver-run/000000F/run-P84ae2390cfc3af.bash.stderr file:

>gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j $nproc -r ../../../quiver-split/refs/000000F/ref.fasta aln-000000F.bam            -o ${fasta_fn},${fastq_fn},cns.vcf
>+ gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000000F/ref.fasta aln-000000F.bam -o cns.fasta,cns.fastq,cns.vcf
>|> 20191030 08:35:11.567 -|- FATAL -|- Run -|- 0x7fef459d57c0|| -|- unsupported sequencing chemistry combination:
    binding kit:        100372700
    sequencing kit:     100356200
    basecaller version: 2.3.0.1.142990

I think that means the actual Falcon version has skipped a previous chemistries. Is there another test set which can you provide to the community instead?

I used the following Falcon version:
falcon-kit 1.5.2 (pip thinks "falcon-kit 1.5.2")
pypeflow 2.3.0

Thanks in advance and best regards
Axel

**Comment by pb-cdunn** [comment]
Yes, I need to upload a new version. It's mostly synthetic data, so the "chemistry" is faked. But we do have a version with updated chemistry...

**Comment by mdeloger** [comment]
+1
It is important to understand actually if pb-assembly do not technically work or if it is related to our dataset.
Thank you very much in advance @pb-cdunn

**Comment by pb-cdunn** [comment]
I updated the chemistry, and the new tarball will be pulled by `git-sym` via **FALCON-examples**. You can see it here:

https://downloads.pacbcloud.com/public/data/git-sym/

called `greg200k-sv2.3.tar` now.
