### ISSUE TITLE
how to change variantCaller options

### ISSUE THREAD

**Issue by chanikyu** [PacificBiosciences/FALCON_unzip#154]
Hello,

I want to change variantCaller algorithm from arrow to plurality.
However, I do not know how to add such option to config file.

Please let me know how to add variantCaller algorithm option to config file?

Thank you

**Comment by gconcepcion** [comment]
it's not possible to change the variant caller without manually editing the scripts. Plurality is a very simple consensus calling algorithm, I would be very skeptical of the results as the algorithm has not been tested for at least 7 years, and never in the context of FALCON assemblies.

What is your use case that you need plurality results?
