### ISSUE TITLE
Error installing FALCON

### ISSUE THREAD

**Issue by cement-head** [PacificBiosciences/FALCON_unzip#156]
I'm trying to install FALCON using the STANDARD method.  I am using Ubuntu 18.04 LTS.

My Python2.7 installation is </usr/local/lib/python2.7>

I do not understand what is meant by ${PREFIX}

Can you please explain?

Would my ${PREFIX} be </usr/local> or </usr/local/lib/python2.7>

Using either one generates this error:

$ pbalign --help
Traceback (most recent call last):
  File "/usr/local/bin/pbalign", line 7, in <module>
    from pbalign.pbalignrunner import main
ImportError: No module named pbalign.pbalignrunner

**Comment by pb-cdunn** [comment]
We do not currently support installation from these repos. Please use Bioconda.

https://github.com/PacificBiosciences/pbbioconda
