### ISSUE TITLE
Which one is the current version of falcon?

### ISSUE THREAD

**Issue by JYLeeBioinfo** [PacificBiosciences/FALCON_unzip#158]
Hi

  I am trying to install FALCON for diploid assembly.

  However, there are so many repositories for falcon and I want to know which one to install.

  It seems to be either this repository or pb-falcon.

  Do they contain the same contents? Or which one should I use ?

Best,

Jinyoung
  
![image](https://user-images.githubusercontent.com/13775022/71232369-086fb980-2335-11ea-934f-3fa88808b152.png)

**Comment by hangch123** [comment]
Hi
Nice to meet you!


&nbsp;I think you should use conda to install pb-falcon, conda install pb-assembly
------------------&nbsp;Original&nbsp;------------------

**Comment by JYLeeBioinfo** [comment]
Thank you!

I successfully installed pb-falcon and pb-assembly using conda.

Best,

Jinyoung
