### ISSUE TITLE
BLASR alignment might take long time for contigs that are mostly simple tandem repeats

### ISSUE THREAD

**Issue by pb-jchin** [PacificBiosciences/FALCON_unzip#16]
Some contigs are mostly simple repeats. The seeding and filling algorithm used in BLASR has trouble to align the reads to those contigs efficiently.  It might make sense to detect shorter contig with low entropy in sequence context and not trying to do phasing on those contigs.

**Comment by pb-cdunn** [comment]
**DBdust** could be used to mask low entropy sections, so at least they would not contribute to daligner overlaps.

**TANmask** could be used to mask tandem repeats. I've added **DAMASKER** to **FALCON-integrate** and made it available in our internal **mobs** build too.

**Comment by pb-jchin** [comment]
DBdust won't help for the short term as we need the SAM/BAM infrastructure for phasing work. Where the TANmask code? I need to take a look before concluding whether it could help or not.

**Comment by pb-cdunn** [comment]
Code is in
* https://github.com/PacificBiosciences/DAMASKER

**Comment by pb-jchin** [comment]
ok. the problem is that we can't use the `Daligner` and `DAZZ_DB` for this yes. We do need something like raw `dust` masking code.

**Comment by mictadlo** [comment]
Any updates on it? Or ngmlr could maybe be used because it might be faster?

**Comment by pb-cdunn** [comment]
We always run `DBdust now`. That might help. If you go to the dazzlerblog, you can learn how to analyze the "dust track" to see how much as been masked.

We are also replacing blasr, hopefully within a few weeks.
