### ISSUE TITLE
Code releases

### ISSUE THREAD

**Issue by frikiluser** [PacificBiosciences/FALCON_unzip#160]
Hi,

As Python2 is no longer supported, FALCON needs to be migrated to Python3 to avoid being dropped from Debian. Debian bug here [0].

It seems last FALCON releases are only available on binary format and also need to be migrated to Python3. Are you already working on a Python3 release? Debian med-team probably can help on that maintenance avoiding drop, fork or efforts duplicity.

[0] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936503

**Comment by pb-cdunn** [comment]
We have python3, but I don't know whether I'm allowed to publish that.

**Comment by pb-cdunn** [comment]
We have pushed the latest falcon code-base for python3. If that helps, you are free to install it.

* https://github.com/PacificBiosciences/pypeflow3
* https://github.com/PacificBiosciences/falcon3
* https://github.com/PacificBiosciences/falcon_unzip3

**Comment by tillea** [comment]
Thanks a lot.  This seems to be helpful.  Would you mind setting release tags on the said repositories.  Debian tries to package what you consider stable code dedicated to a wide user base.  Without release tags its not clear what "random" commit might fulfill this criterion.  Kind regards, Andreas.

**Comment by pb-cdunn** [comment]
We can create some release tags, though this is not actively developed anymore. Is this still an issue for you?

**Comment by tillea** [comment]
On Thu, Sep 10, 2020 at 09:32:41AM -0700, Christopher Dunn wrote:
> We can create some release tags, though this is not actively developed anymore. Is this still an issue for you?

It would be nice if at least your latest release would be tagged - no need to go back in history.
Kind regards, Andreas.
