### ISSUE TITLE
Is it possible to run falcon_unzip on HGAP4 output from SMRTlink ?

### ISSUE THREAD

**Issue by Philosamia** [PacificBiosciences/FALCON_unzip#161]
Hi, 
I just finished assembling my genome on SMRTlink GUI v8. 
Is it possible to run Falcon_unzip command line on HGAP4 output from SMRTlink GUI, 
or do I have to re-run falcon on command-line and then run unzip?

Thanks

**Comment by pb-cdunn** [comment]
You can try `python3 -m falcon_kit.mains.hgap4_adapt --help`. In theory, that can create symlinks to make a smrtlink run look like a falcon run, so falcon_unzip can then be used.

Unfortunately, smrtlink directory names may have changed, and we have not been keeping the adapter up-to-date. But it _might_ work for you.
