### ISSUE TITLE
Input data for Falcon-Unzip

### ISSUE THREAD

**Issue by mentorlg** [PacificBiosciences/FALCON_unzip#169]
Hi, I have questions about Falcon-Unzip assembler.

Is it possible to assemble reads using only Falcon-Unzip?
In the tutorial, Falcon-Unzip uses Falcon results as input.
Do I have to assemble contigs prior to use Falcon-Unzip..?

If not, can I use 'assembled contigs from other assemblers' as input for Falcon-Unzip?
I'm not sure that Falcon-Unzip is compatible with other assemblers like Canu, SOAPdenovo2, Platanus...and so on.

Or... is it impossible using just reads data as input of Falcon-Unzip?

I look forward to hearing from you soon.

Sincerely,
Amelia

**Comment by gconcepcion** [comment]
answered here:
https://github.com/PacificBiosciences/FALCON/issues/715#issuecomment-882767168
