### ISSUE TITLE
falcon_unzip and fc_unzip.cfg

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/FALCON_unzip#21]
I have just finished a falcon fun and want to use FALCON_unzip to construct haplotype specific contigs.
I saw in the example fc_unzip.cfg that "job_type = SGE". For Falcon you have mentioned that we can set "job_type = local", so is it also true for Falcon_Unzip? Thanks!

**Comment by pb-jchin** [comment]
`FALCON_unzip` can use the `local` option but it has limited test. The AWS instance as an example uses the local mode.

**Comment by danshu** [comment]
Is there any reference for setting the config file in the local mode?

**Comment by peterdfields** [comment]
Not sure my own setup would apply to yours but using the following was where I started and it seems to work:

[General]
job_type = local

[Unzip]
input_fofn= input.fofn
input_bam_fofn= input_bam.fofn

smrt_bin=/home/peter/bioinformatics/smrtlink/install/smrtlink-fromsrc_3.0.5.175021,175083-175021-174993-174993/bundles/smrttools/smrtcmds/bin/

jobqueue =
sge_phasing=
sge_quiver=
sge_track_reads=
sge_blasr_aln=
sge_hasm=
unzip_concurrent_jobs = 1
quiver_concurrent_jobs = 1

You'll likely need to tinker with the unzip_concurrent_jobs and quiver_concurrent_jobs to optimize your  run.
