### ISSUE TITLE
SMRT Analysis v3 download info no longer works

### ISSUE THREAD

**Issue by peterdfields** [PacificBiosciences/FALCON_unzip#24]
Following steps on https://github.com/PacificBiosciences/FALCON_unzip/wiki/FAQ
suggested the requested files are no longer available. 

Is it just the requested file names need to be changed to the current versions?

**Comment by peterdfields** [comment]
The file names just need to be changed to: smrtlink_3.0.5.175021.run and smrtlink_3.0.5.175021.run.md5

**Comment by pb-jchin** [comment]
@peterdfields thanks.
