### ISSUE TITLE
task_hasm() dies on missing ctgs

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/FALCON_unzip#28]
Perhaps this is proper behavior, but in the deduping loop, if a ctg directory doesn't exist, the script exits:

`for f in `cat ../reads/ctg_list `;do cd $WD/$f; fc_dedup_h_tigs.py $f; done`

To get past this, I simply rewrote it as

```
for f in `cat ../reads/ctg_list`;do
if [ -d "$WD/$f" ]; then
cd $WD/$f
fc_dedup_h_tigs.py $f
fi
done

```

I'm not sure what a missing ctg directory implies - for example, if that's a critical error of some sort, and needs to be dealt with.  If not, this patch a least allows the run to complete.

**Comment by jfass** [comment]
Check the "Possible MUMmer issue ..." issue ... doesn't answer your question, but there's other discussion of workarounds.

**Comment by yingzhang121** [comment]
I had the same issue.  So I just manually created the directory for all the names in ctg_list.  It seems this way can push fc_unzip.py forward.  However, I do suspect whether the missing contig will be correctly incorporated into the multiple all_* output files.
