### ISSUE TITLE
BAM file necessary for quiver step?

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [PacificBiosciences/FALCON_unzip#30]
Did I understand that correctly? For the quiver step in falcon_unzip I have to provide the reads in BAM format?

What is the most easy way to convert RSII data to BAM format?

**Comment by pb-jchin** [comment]
yes. PacBio is moving the read data format to BAM to easy some engineering work. It is a good thing.  There is code called `bax2bam` that convert the `bax.h5` to BAM file (with option `--subread`) in SMRTAnalysis 3.0.0+.

**Comment by MichaelsGITIGIT** [comment]
Great! Thanks for the quick aswer
