### ISSUE TITLE
Version question

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/FALCON_unzip#35]
Hi
I assembled a genome "recently" with FALCON 0.4.0 - which worked great by the way!
Now we thought that for that particular project FALCON-UNZIP might be very informative and I wanted to give it a try.
I am a little bit confused now regarding the correct version of FALCON-UNZIP. Obviously FALCON is now already at version 0.7 and installing the dependencies for FALCON-UNZIP I realized that everything seems to be switching now to the new BAM standard in smrtpipe3.0.

So I guess my question is, whether I can run FALCON-UNZIP with FALCON 0.4.0, or what version of FALCON-UNZIP I would have to use in order to be compatible.
Another option would be to install FALCON 0.7.0 and the latest FALCON-UNZIP but will this be compatible with the output from FALCON 0.4.0 ?
The genome is > 2Gbp and re-running currently not an option.

Thanks for any clarification
Cheers

**Comment by pb-jchin** [comment]
@ebioman When I developed the FALCON-UNZIP, I have to use a frozen version of FALCON (v.0.4.*).  However, FALCON-UNZIP only depends on the files / directory structures which I don't think that has been changed up to v.0.7.   It does need the final `las` files for both `0-` and `1-` stages.

**Comment by ebioman** [comment]
Thank you very much - clarified things.
