### ISSUE TITLE
task "hasm.sh-hasm-hasm" took very long time

### ISSUE THREAD

**Issue by lxliangit** [PacificBiosciences/FALCON_unzip#37]
Hi the team,

My FALCON_unzip running for human genome has already been running for more than 2 weeks! Actually, it has been hovering the following commands of task "hasm.sh-hasm-hasm" for 12 days:

```
FALCON-integrate/FALCON-integrate_78e1569/fc_env/bin/python \
FALCON-integrate/FALCON-integrate_78e1569/fc_env/bin/fc_ovlp_filter_with_phase.py \
--fofn ../../2-asm-falcon/las.fofn --max_diff 120 --max_cov 120 --min_cov 1 --n_core 12 \
--min_len 2500 --db ../../1-preads_ovl/preads.db --rid_phase_map ./rid_to_phase.all
```

The following is my configuration:
```
[General]
job_type = SGE

[Unzip]
sge_blasr_aln = -pe OpenMP 24 -q long.q -l h_rt=720:00:00,mem_free=64G,h_vmem=64G

smrt_bin = /mnt/projects/liuxl/ctso4_projects/liuxl/Tools/pitchfork_my_python/pitchfork/dist/bin

sge_phasing = -pe OpenMP 12 -q long.q -l h_rt=720:00:00,mem_free=64G,h_vmem=64G

sge_hasm = -pe OpenMP 24 -q long.q -l h_rt=720:00:00,mem_free=64G,h_vmem=64G

sge_track_reads = -pe OpenMP 12 -q long.q -l h_rt=720:00:00,mem_free=64G,h_vmem=64G

unzip_concurrent_jobs = 64
```

Is that too long to run?

**Comment by pb-jchin** [comment]
The step is usually fast but it could use too much memory for now (see https://github.com/PacificBiosciences/FALCON_unzip/issues/10). If that is the case for you computation node, you need to check if the process causes swapping. If so, you will need to reduce the amount of parallel process to reduce memory usage.

**Comment by lxliangit** [comment]
Hi @pb-jchin,

Hope this issue won't bother you too much. It actually caused by some stupid file path mistakes made by myself. I closed the threshold yesterday immediately when I found the reason.

Thank you very much for your prompt response.

**Comment by pb-jchin** [comment]
@lxliangit, glad that you fin the root cause.  Sometimes, it is tricky for such debugging as it not easy to know the exact execution environment.
