### ISSUE TITLE
Sharing scripts for generating Figure3 in FALCON-Unzip preprint.

### ISSUE THREAD

**Issue by JinfengChen** [PacificBiosciences/FALCON_unzip#38]
Hi Jason,

Can you share the script to generate Figure 3 in preprint of FALCON and FALCON-Unzip. I think it is great way to compare the contigs from FALCON and FALCON-Unzip to a reference genome. I am trying use that in my assembly instead of IGV.

Thanks.
Jinfeng

Figure 3. SNP density and Structural Variations in the FALCON-Unzip F1 Arabidopsis assembly. The plot shows the primary contigs and haplotigs aligned to chromosome 4 of the TAIR reference assembly as grey line segments. Blue and Red colored dots show the number of Col-0 and Cvi-0 specific SNPs, respectively, per 50 kbp region of the assembled contig. The vertical orange lines indicate the centromere locations. The short vertical tick marks above the grey lines indicate the structural variations against Col-0 (blue) and Cvi-0 (red).

**Comment by peterdfields** [comment]
Was the script for generating this figure ever posted?

**Comment by JinfengChen** [comment]
No. No body response.

**Comment by pb-jchin** [comment]
It is tailored to a specific genome and a specific reference. I am not sure how useful it is and if your genome is different, you will need different visualization.

**Comment by JinfengChen** [comment]
Thanks, Jason. I think it is a quite useful way to visualize the assembly when reference genome available. I am working on a heterozygous citrus genome where the reference genome available is haploid. The heterozygous snps in the citrus genome are not evenly distributed and cause lots a problem in assembly. I plot the contigs along chromosomes to figure out which parts of genome were poorly assembled. I am still working on improving assembly. 
Thanks.

Jinfeng

**Comment by kevlim83** [comment]
@pb-jchin 
Hi Jason,
We have used falcon unzip with great success. I would also like to generate some plots to compare the variation in the heterozygous genome that we are working with. Could you please share the same script with me? I am happy to adapt the script, so that I dont have to reinvent the wheel.

Thanks!

**Comment by pb-jchin** [comment]
Hi, @kevlim83 those are really just "scripts" tailored toward to Arabidposis and particular runs with http://assemblytics.com.  My suggestion is to use nucmer to align genome to genome and make sure you understand how repeat matching are processed.  Than you can use Assemblytics to generate some summary.
