### ISSUE TITLE
FileNotExistError: "No such file:'/data/falcon/0-rawreads/raw_reads.db' on '......'"

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/FALCON_unzip#40]
Hi,

I'm running falcon_unzip and I have this error:
"FileNotExistError: "No such file:'/data/falcon/0-rawreads/raw_reads.db' on '......'""
Because I ran falcon using preads, so the "0-rawreads" is definitely almost empty. Do I need to copy those files from the "0-rawreads" directory of a previous run?

Best,
Quan

**Comment by pb-cdunn** [comment]
How did you solve this? It is possible that a recent change broke the preads entry (which should skip the 0- tasks).

**Comment by danshu** [comment]
I failed again when I copied "0-rawreads" directory of a previous run, with this error message:
"DBshow: Cannot open .../0-rawreads/.raw_reads.idx for 'r'
No handlers could be found for logger "pypeflow.task"
Since I can not find .raw_reads.idx under "0-rawreads",  I just rerun falcon from the begining because I'm not sure whether I have deleted these files previously or not. Then I'm running falcon_unzip now.

**Comment by pb-cdunn** [comment]
I don't understand that at all. The `.raw_reads.*` files are still in `0-rawreads`. Maybe you can run UNIX `find .` to look for it? It's hard to say remotely.

> No handlers could be found for logger "pypeflow.task"

You need to initialize the logger. You can use a logging config from `FALCON-examples/run/synth0/`, or you can google "python logging config".

> Since I can not find .raw_reads.idx under "0-rawreads", I just rerun falcon from the begining because I'm not sure whether I have deleted these files previously or not.

Please let us know if you identify and solve a bug. This is open-source software. We rely on user submissions for many things.

**Comment by danshu** [comment]
By "locate raw_reads.idx", I can find .raw_reads.* files in 0-rawreads of previous run using raw reads but not when I copied that directory to current run using preads. So is it due to that the command "cp" can not actually copy these .raw_reads.* files?

**Comment by pb-cdunn** [comment]
You probably needed to use something like `cp -r` or `rsync` to copy a directory tree recursively. If you copy sets of files using `*`, then you would need to set something like `dotall` (if using bash) in your shell.

**Comment by danshu** [comment]
@pb-cdunn Thanks!
