### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by mahulchak** [PacificBiosciences/FALCON_unzip#41]
Is falcon_unzip incompatible with smrtanalysis versions prior to 3.0? I'm using 2.3.0p5 and the scripts for.blasr readmapping are not working properly. I can give you more details if needed.
Thanks.

**Comment by pb-jchin** [comment]
No. FALCON_unzip uses bam file (instead of hdf5 file base) based consensus pipeline which only exists after 3.0.

**Comment by mahulchak** [comment]
I see.  I will install the new version and try again.

**Comment by mahulchak** [comment]
Is v3.0 available for download? I can find 2.3.0 but not any version after
that.
Thanks.

**Comment by peterdfields** [comment]
There is mention of the download in the FAQ but the address and login no longer work: 

https://github.com/PacificBiosciences/FALCON_unzip/wiki/FAQ

**Comment by mahulchak** [comment]
No it does not work! Where can I find smrtanalysis v3.0 or later?

**Comment by pb-jchin** [comment]
Please contact the vendor who gives you the data, ask them to file a request ticker through the commercial customer support system. I can't comment on the official software here.
