### ISSUE TITLE
Failed to recurse into submodule path 'FALCON'

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON_unzip#44]
Hi
```
git clone --recursive https://github.com/PacificBiosciences/FALCON_unzip.git
Cloning into 'FALCON_unzip'...
remote: Counting objects: 656, done.
remote: Total 656 (delta 0), reused 0 (delta 0), pack-reused 656
Receiving objects: 100% (656/656), 159.50 KiB | 215 KiB/s, done.
Resolving deltas: 100% (345/345), done.
error: unable to create symlink LICENSE (File name too long)
Submodule 'FALCON' (git@github.com:PacificBiosciences/FALCON.git) registered for path 'FALCON'
Cloning into 'FALCON'...
Enter passphrase for key '/home/michallorenc/.ssh/id_rsa': 
remote: Counting objects: 3696, done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 3696 (delta 61), reused 0 (delta 0), pack-reused 3608
Receiving objects: 100% (3696/3696), 1.32 MiB | 582 KiB/s, done.
Resolving deltas: 100% (2619/2619), done.
Submodule path 'FALCON': checked out 'a4ef0b3e7ff461bbe5512f31ee0e3b5c15fba04e'
Submodule 'DALIGNER' (git://github.com/pb-jchin/DALIGNER.git) registered for path 'DALIGNER'
Submodule 'DAZZ_DB' (git://github.com/pb-jchin/DAZZ_DB.git) registered for path 'DAZZ_DB'
Submodule 'pypeFLOW' (git://github.com/pb-jchin/pypeFLOW.git) registered for path 'pypeFLOW'
Cloning into 'DALIGNER'...
remote: Counting objects: 339, done.
remote: Total 339 (delta 0), reused 0 (delta 0), pack-reused 339
Receiving objects: 100% (339/339), 433.00 KiB | 170 KiB/s, done.
Resolving deltas: 100% (219/219), done.
fatal: reference is not a tree: f5ca2a0bb2a5f939da57cc842e02fc7cbf075407
Cloning into 'DAZZ_DB'...
remote: Counting objects: 281, done.
remote: Total 281 (delta 0), reused 0 (delta 0), pack-reused 281
Receiving objects: 100% (281/281), 283.54 KiB | 180 KiB/s, done.
Resolving deltas: 100% (192/192), done.
Submodule path 'DAZZ_DB': checked out '1b53112462bfa3b391c2d7538fcdcd278fae62e3'
Cloning into 'pypeFLOW'...
remote: Counting objects: 1514, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 1514 (delta 38), reused 1 (delta 1), pack-reused 1453
Receiving objects: 100% (1514/1514), 2.15 MiB | 513 KiB/s, done.
Resolving deltas: 100% (812/812), done.
Submodule path 'pypeFLOW': checked out '23a0a9da3ab4584a59dafc35243987ff74a52b05'
Unable to checkout 'f5ca2a0bb2a5f939da57cc842e02fc7cbf075407' in submodule path 'DALIGNER'
Failed to recurse into submodule path 'FALCON'
```

What did I do wrong?

Thank you in advance.

Mic

**Comment by pb-jchin** [comment]
You will need to first install FALCON and test it working before installing FALCON_unzip.
 
Check out this FALCON with this tag https://github.com/PacificBiosciences/FALCON-integrate/tree/funzip_052016  
 
please follow the instruction to install the checked out version
 
https://github.com/PacificBiosciences/FALCON-integrate/blob/master/README.md   
 
However, currently FALCON is under heavily refactoring the instruction might be ahead of the version  funzip_052016.
 
I am not sure what you execution environment.  Some OS like Python's virtualenv, some does not.   If your system can handle virtualenv, you should build the FALCON within a virtualenv. Then you should do some testing to assemble a small genome with FALCON to get used to it.
 
Once this is working, you can install FALCON_unzip by cloning the repository and install to the same virtualenv.
 
If not sure and you are familiar with AWS, you can try to see a preinstalled case following this http://www.nature.com/nmeth/journal/vaop/ncurrent/extref/nmeth.4035-S5.pdf

**Comment by mictadlo** [comment]
Thank you, Michael and @pb-jchin. Before I got lost I did the following steps.


1. `$ git clone https://github.com/PacificBiosciences/FALCON-integrate.git`
2. `$ git checkout funzip_052016`
3. `$ git submodule update --init`
4. ```$ make init` but here I recieved the following error:
git submodule update --init --depth=1 virtualenv
Usage: git submodule [--quiet] add [-b branch] [-f|--force] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--] [<path>...]
make: *** [init] Error 1
```

I could not fine `config-standard.sh` and `config-edit.sh` as described [here](https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation).

What did I do wrong?

Thank you in advance.

Mic

**Comment by pb-cdunn** [comment]
You have an old version of **git**. If you cannot update it, there us a simple work-around: Modify the makefile to drop `--depth=1`. It will be a little slower, since you will end up with the entire history of the open-source **virtualenv** module.

**Comment by mictadlo** [comment]
Thank you, but after suggestion from @pb-cdunn `make init` did not produce `env.sh`:
```
$ make init
git submodule update --init virtualenv
git submodule update --init
$ source env.sh
-bash: env.sh: No such file or directory
```

What did I miss?

Thank you in advance.

Mic

**Comment by pb-cdunn** [comment]
```diff
commit 7c6c797ed0a95ed00349ac976aaa1db7710b87a2
Author: Christopher Dunn <cdunn@pacificbiosciences.com>
Date:   Sun Jun 19 19:03:19 2016

    Several styles of installation

diff --git makefile makefile

 init:
        git submodule update --init
+       cp -f default-env.sh env.sh
```
I think your commit of FALCON-integrate is older than that. You're using `0.4.2`? Ok. For the older version, you need to get virtualenv installed first. (I should have kept a README in there.) You need to do this:

    make init
    make virtualenv
    make check
    ./fc_env/bin/activate
    make install

**Comment by mictadlo** [comment]
Hi, I got a new error:
```
> make virtualenv
mkdir -p /gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env
python2.7 virtualenv/virtualenv.py --no-site-packages  --always-copy /gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env
New python executable in /gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env/bin/python2.7
Not overwriting existing python script /gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env/bin/python (you must use /gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env/bin/python2.7)
/gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env/bin/python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/gpfs1/homes/michallorenc/tmp/FALCON-integrate' (should be u'/gpfs1/homes/michallorenc/tmp/FALCON-integrate/fc_env')
ERROR: virtualenv is not compatible with this system or executable
make: *** [virtualenv] Error 100
```

Did I miss anything?

Thank you in advance

Mic

**Comment by pb-cdunn** [comment]
As Jason pointed out, lots of people have problems with **virtualenv** on various systems. We cannot help with that.

I suggest using a more recent version of FALCON-integrate. Then you can follow the wiki for a Python "user install". You can google `PYTHONUSERBASE` for more info. Very standard stuff.

I'm not whether the very latest FALCON-integrate (1.8.0) will work for you because we have changed some directories for some intermediate files. We simply haven't had time to keep FALCON_unzip in sync, but it will *probably* work. (I plan to work on that within the next 2 weeks.) You can also use an earlier release, but if you discover a specific problem with a directory name, we will update FALCON_unzip immediately on a branch for you. So I'd recommend 1.8.0.

Or try a system where virtualenv works.

**Comment by mictadlo** [comment]
Hi, Thank you, the `1.8.0` version has worked. We getting any time our first Fruit Genome sequence and we look forward to try as soon as possible FALCON_unzip.
