### ISSUE TITLE
from: can't read /var/mail/falcon_unzip.ovlp_filter_with_phase

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/FALCON_unzip#46]
Hi,

I'm running falcon_unzip and I have the following error when running `fc_ovlp_filter_with_phase.py --fofn ../../2-asm-falcon/las.fofn --max_diff 120 --max_cov 120 --min_cov 1 --n_core 12 --min_len 2500 --db ../../1-preads_ovl/preads.db --rid_phase_map ./rid_to_phase.all > preads.p_ovl" in "hasm.sh"`
```
from: can't read /var/mail/falcon_unzip.ovlp_filter_with_phase
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
import: unable to open X server `localhost:10.0' @ error/import.c/ImportImageCommand/364.
/tools/assembler/FALCON_unzip-master/src/py_scripts/fc_ovlp_filter_with_phase.py: 4: /tools/assembler/FALCON_unzip-master/src/py_scripts/fc_ovlp_filter_with_phase.py: Syntax error: word unexpected (expecting ")")"
```
Best,
Quan

**Comment by danshu** [comment]
When I run using MobaXterm, the only message is ""from: can't read /var/mail/falcon_unzip.ovlp_filter_with_phase" and "fc_ovlp_filter_with_phase.py" keeps running without exit.

**Comment by danshu** [comment]
I solved this problem by "source env.sh" because I installed falcon_unzip unter "fc_env". So I want to know that do I need to source again everytime I run falcon or falcon_unzip?

I deleted "1-hasm" directory under "3-unzip" and rerun fc_unzip.py again. Can falcon_unzip identify those already finished jobs (track_reads and fetch_reads) and then work properly?

**Comment by danshu** [comment]
Then here is another error:
fc_graphs_to_h_tigs.py --fc_asm_path ../../2-asm-falcon/ --fc_hasm_path ./ --ctg_id all --rid_phase_map ./rid_to_phase.all --fasta ../../1-preads_ovl/preads4falcon.fasta
"IOError: [Errno 2] No such file or directory: '../../1-preads_ovl/preads4falcon.fasta'"

It seems that falcon_unzip expects there preads to be in the "1-preads_ovl" directory, while actually these preads are under "1-preads_ovl/db2falcon". Is this a bug or a confict of the version of falcon and falcon_unzip I used? I'm using FALCON-integrate 0.7+git.4ef2433d41140c2a232fa7f0ea3db4f6b39ed84f and Falcon_unzip version 0.1.0.

**Comment by danshu** [comment]
I copied preads4falcon.fasta to "1-preads_ovl" directory. Can this solve the problem?

**Comment by pb-jchin** [comment]
@pb-cdunn might have changed where the `pread4falcon.fasta` location, you can just make a symlink to the`1-pread_ovl` for now.

**Comment by pb-cdunn** [comment]
I'll push a quick fix tonight. Expect a proper fix soon.

**Comment by pb-cdunn** [comment]
Try the tip of the `master` branch. Not tested yet.
