### ISSUE TITLE
Falcon Unzip documentation

### ISSUE THREAD

**Issue by yingzhang121** [PacificBiosciences/FALCON_unzip#47]
Hi,

Is there a detailed documentation of how to install and run Falcon Unzip anywhere?

Best,
Ying

**Comment by pb-jchin** [comment]
Here is the current status https://github.com/PacificBiosciences/FALCON_unzip/blob/master/README.md

You will get the algorithm idea and general method from preprint. For other software related support, please see the `README.md`.
