### ISSUE TITLE
[E::hts_open_format] fail to open file '../4-quiver/reads/000011F_036.sam

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/FALCON_unzip#48]
Hi,

I have finished 3-unzip successfully but the resulting all_p_ctg.fa is about 25Mb smaller than p_ctg.fa and have less sequences. So does all_p_ctg.fa only contain those contigs that have bubbles, so that those sequences that can not phased are not included or does Falcon_unzip have some filtering on contig length?

But the "fc_quiver.py" step failed with the follwoing error message:
```
"001301F 9[E::hts_open_format] fail to open file '../4-quiver/reads/000011F_036.sam'
../track_reads_h.sh: line 13: 13711 Segmentation fault      (core dumped) fc_select_reads_from_bam.py input_bam.fofn"
```
So here are 4 my questions:
1. what's the cause of this error? 
2. What I also want to know before I run fc_quiver.py again is that where are thoese missing sequences? I would like also to add those sequences for quiver polishing. 
3. What's the differences between "fc_quiver.py" and quiver "variantCaller --algorithm=quiver"? Can I instead using "variantCaller --algorithm=quiver" to polish my contigs, since I can run this pipeline successfully on p_ctg.fa. 
4. If "fc_quiver.py" is a must following "fc_unzip.py", can I just delete "4-quiver" directory and run "fc_quiver.py" again? For Falcon I know that I can delete subjobs of previous run and then rerun following jobs again, but I'm not sure about "fc_quiver.py". 

Best,
Quan

**Comment by danshu** [comment]
Actually I can not find "000011F_036.sam" under "4-quiver/reads/". I only find 
"000011F_034 656
000011F_035 228
000011F_036 1107
000011F_037 898
000011F_038 256" 
in the track_reads_h.sh.log.

**Comment by pb-jchin** [comment]
some associate contigs are very similar to the primary, those got filtered out.

**Comment by danshu** [comment]
Can I add back those contigs for polishing? Is "fc_quiver.py" able to polish after adding some contigs or should I use "variantCaller --algorithm=quiver"?

**Comment by jessyjli** [comment]
I have had this exact same problem recently. It turned out to be that the system limits the number of opened files. After increasing the limit, the error is gone.

**Comment by pb-cdunn** [comment]
@jessyjli, yes, we need to avoid opening so many files.

**Comment by danshu** [comment]
@jessyjli Thanks for you help! I will try this solution now. So exciting!

**Comment by danshu** [comment]
Have successfully finished the last quiver polishing step after increasing the system limit. Thanks again for everyone!
