### ISSUE TITLE
20161111|121503| 46693| ERROR: mummer and/or mgaps returned non-zero

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/FALCON_unzip#50]
Hi,

I have finished 3-unzip and have output files uner "3-unzip". However, I just noticed that for many contig directories under "/data/jellyfish/Pacbio/falcon/san_falcon_t7_run3/3-unzip/1-hasm", I have "nucmer.error" files, which have error messages like "20161111|121503| 46693| ERROR: mummer and/or mgaps returned non-zero". 
What does these errors mean? Will they influence the results of 3-unzip? 

Best,
Quan

**Comment by pb-jchin** [comment]
you can ignore some nucmer error.  This code is still in its early stage, some boundary cases are not check before sending to nucmer and we might eventually replace nucmer by something else.
