### ISSUE TITLE
FALCON_unzip reverts to job_type=local

### ISSUE THREAD

**Issue by roblehmann** [PacificBiosciences/FALCON_unzip#58]
Hi,
I'm trying to run FALCON_unzip on the ecoli example. I have set:
```
[General]
job_type = SLURM
```
However, it only runs in local mode: 
```
[INFO]job_type='local', job_queue='UNSPECIFIED_QUEUE', sge_option=None, use_tmpdir=None, squash=False`
```
Interestingly, e.g. the 3-unzip/reads/task.json states the job_type is SLURM.

The revisions:
FALCON_unzip:
38de578054fc62ba6087ab6c596371fb85417c1e
FALCON-integrate:
cd3770021fa1884caa141953fc27a79918930ade
FALCON:
3b90cca3af5435b2a3b11e5f529befe718191368

thanks in advance

**Comment by pb-jchin** [comment]
FALCON_unzip for non-SGE is not tested much. If your genome is small, local mode might be the way to go for now.

**Comment by pb-cdunn** [comment]
I think this is fixed with the latest pypeflow and FALCON_unzip.
