### ISSUE TITLE
updated falcon-unzip not reading cfg file correctly

### ISSUE THREAD

**Issue by mahulchak** [PacificBiosciences/FALCON_unzip#67]
Hello,
I had run falcon-unzip before but after I updated it from github couple of days back, the queue name provided in the cfg file is not being read by falcon-unzip. Following are the first few lines from all.log file -

2017-01-29 20:12:45,785 - fc_run - INFO - Setup logging from file "None".
2017-01-29 20:12:45,790 - pypeflow.simple_pwatcher_bridge - WARNING - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/fc_env/lib/python2.7/site-packages/pwatcher/fs_based.pyc'>
2017-01-29 20:12:45,790 - pypeflow.simple_pwatcher_bridge - INFO - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/fc_env/lib/python2.7/site-packages/pwatcher/fs_based.pyc'>
2017-01-29 20:12:45,867 - pypeflow.simple_pwatcher_bridge - INFO - job_type='SGE', job_queue='default', sge_option=None, use_tmpdir=None, squash=False

Not sure why it resorts to default for the queue name! Interestingly, it can read all other options from the cfg file (e.g. job_type,sge_phasing etc.)  Any idea why it is unable to read only the job_queue option from the cfg file?
Many thanks.

**Comment by pb-cdunn** [comment]
Maybe something wasn't quite updated. There are my current commits:
```
$ git submodule
 7c09c812051983ac269d01840a1e8e8b982a06f6 DALIGNER (V1.0-82-g7c09c81)
 5726269b6e72d7388020b5f69748f0c34e384584 DAMASKER (heads/master)
 925dd7632e420568d8446d30b28d22dbf63b152e DAZZ_DB (V1.0-47-g925dd76)
 89726800346d0bed15d98dcc577f4c7733aab4b1 DEXTRACTOR (V1.0-18-g8972680)
 7a6ac0d8e8492c64733a997d72a9359e1275bb57 FALCON (0.2JASM-534-g7a6ac0d)
+9960e389a18a5d2159da8f623428ed0fe992b771 FALCON-examples (heads/master)
 ac46547070f7e1465ab9af344766890b7cf4ec73 FALCON-make (heads/master)
 483836854e1bafb6e40cf17f3a9382efe351daad git-sym (heads/master)
 f928267429f8cb456191b518a6d0de966b772ddc pypeFLOW (v0.1.0-169-gf928267)
```
If those look the same, then maybe you did not update completely. Try removing your PYTHON_USER_BASE directory and re-installing everything. It takes only a few seconds.

Otherwise, you might have to try to debug this yourself. There must be an explanation.

**Comment by mahulchak** [comment]
I have updated everything. Still FALCON-examples is different
$ git submodule
 7c09c812051983ac269d01840a1e8e8b982a06f6 DALIGNER (heads/master)
+5726269b6e72d7388020b5f69748f0c34e384584 DAMASKER (heads/master)
+925dd7632e420568d8446d30b28d22dbf63b152e DAZZ_DB (heads/master)
+89726800346d0bed15d98dcc577f4c7733aab4b1 DEXTRACTOR (V1.0-18-g8972680)
 7a6ac0d8e8492c64733a997d72a9359e1275bb57 FALCON (0.2JASM-534-g7a6ac0d)
 12a5bc2a4dec59463be96bf65519777ce75d9611 FALCON-examples (heads/master)
 ac46547070f7e1465ab9af344766890b7cf4ec73 FALCON-make (heads/master)
 483836854e1bafb6e40cf17f3a9382efe351daad git-sym (heads/master)
+f928267429f8cb456191b518a6d0de966b772ddc pypeFLOW (v0.1.0-169-gf928267)

**Comment by mahulchak** [comment]
I figured it out. sge_queue option is only read if it's listed under 'General' and not 'Unzip' in the config file (according to the unzip.py script). I think earlier it was being read even if it was listed under 'Unzip'.
Thanks.

**Comment by pb-cdunn** [comment]
I'll add code to warn in this case. We already warn for unused options in the `General` section.
