### ISSUE TITLE
steps for install and running FALCON_unzip

### ISSUE THREAD

**Issue by wsuplantpathology** [PacificBiosciences/FALCON_unzip#72]
Hello everyone:

I wonder could somebody please write a short summary of steps for installing and running FALCON. Many thanks.

**Comment by wsuplantpathology** [comment]
solved.

I'd be glad to help if somebody needs such steps.

**Comment by yilunhuangyue** [comment]
Hi, could you please sent the steps to me? I have some problem running Falcon_unzip. My e-mail is yilunhuangyue@webmail.hzau.edu.cn.
Thanks a lot.

**Comment by chad388** [comment]
Hi, wsuplantpathology
Could you please send the steps for installing and running Falcon_unzip to me as well. 
My email is: ctomlins@wustl.edu

**Comment by wsuplantpathology** [comment]
Hi @chad388 @yilunhuangyue :

I realize the install steps may be different on different OS platforms, here is general steps:
1) make sure you have all required executables installed, following https://github.com/PacificBiosciences/FALCON_unzip/wiki
2) I use this install pipline
http://pb-falcon.readthedocs.io/en/latest/quick_start.html

The following is my specific steps in my system:
```
export LD_LIBRARY_PATH=/your/library/path/ # e.g.: blasr
export PERL5LIB=/your/perl/lib # e.g.: some perl libraries may be need
cd FALCON-integrate/
git checkout master
make init
source env.sh
make config-edit-user
make -j all
export PYTHONUSERBASE=/your/path/to/FALCON-integrate/fc_env
cd FALCON_unzip/
python setup.py install --prefix=/your/path/to/FALCON-integrate/fc_env
export PYTHONUSERBASE=/your/path/to/FALCON-integrate/fc_env
export PATH=$PATH:{PYTHONUSERBASE}/bin:/your/path/to/graphviz-2.40.1/bin:/your/path/t0/SDL2-2.0.5/bin:/your/path/to/samtools-0.1.19:/your/path/to/pitchfork/bin:/data/chen/software/GenomicConsensus-smrtanalysis-3.0.2/bin:$PATH # you need install all these tools first
bash --init-file /data/chen/software/pitchfork/setup-env.sh # I don't know why, but with this step 'blasr' will run successfully
fc_unzip.py fc_unzip.cfg

One important tip:
!!! change 
!!! /data/chen/software/FALCON_unzip/falcon_unzip/unzip.py Line 90
Original: {samtools} sort tmp_aln.bam -o {ctg_id}_sorted.bam
After: {samtools} sort tmp_aln.bam -o {ctg_id}_sorted.bam > {ctg_id}_sorted.bam
!!! same change /data/chen/software/FALCON_unzip/build/lib/falcon_unzip/unzip.py
##again, I don't know why, without these changes my run failed in blasr step, but after I changed this, blasr step was succeed. 

Good luck

**Comment by pb-cdunn** [comment]
```
Original: {samtools} sort tmp_aln.bam -o {ctg_id}_sorted.bam
After: {samtools} sort tmp_aln.bam -o {ctg_id}_sorted.bam > {ctg_id}_sorted.bam
```
That's really weird. `-o` *means* "dump to that file". What version of **samtools** are you using?

**Comment by chad388** [comment]
Thank you wsuplantpathology for the details. 
This is very helpful!

**Comment by pb-cdunn** [comment]
@chad388 or @wsuplantpathology, What version of samtools are you using?

**Comment by wsuplantpathology** [comment]
Hi @pb-cdunn @chad388 

I was using samtools 0.1.19. Probably it's the issue. I didn't check it with new version (e.g.: 1.3.1).
