### ISSUE TITLE
LD_LIBRARY_PATH is resetting

### ISSUE THREAD

**Issue by ascendo** [PacificBiosciences/FALCON_unzip#78]
Hello Jason,

During the Phasing step, LD_LIBRARY_PATH is resetting.

I compiled BLASR with pitchfork.

I use SGE for job submitting and after job submitting the LD_LIBRARY_PATH seems to be reset.

So the BLASR couldn't find the library and generated error.

Do you have any idea about this situation?

Best,

Won

**Comment by ascendo** [comment]
I couldn't find any evidence and i hacked code.

**Comment by pb-cdunn** [comment]
I'd like to look into this. Could you post your `.ini` settings?

**Comment by ascendo** [comment]
Here is my cfg file.

[General]
job_type = SGE


[Unzip]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn
input_bam_fofn= input_bam.fofn

# The length cutoff used for seed reads used for initial mapping

smrt_bin=/scratch/wyim/pacbio/bin/

job_queue = common.q
jobqueue = common.q
sge_phasing = -pe SharedMem 2
sge_quiver = -pe SharedMem 2
sge_track_reads= -pe SharedMem 2
sge_blasr_aln= -pe SharedMem 2
sge_hasm= -pe SharedMem 2
use_tmpdir=/home/wyim/scratch/tmp/
quiver_concurrent_jobs = 500
unzip_concurrent_jobs = 500

**Comment by pb-cdunn** [comment]
Looks fine. I suggested looking for the actual `qsub` call, to see what flags are actually used. You should see `-V`:
```
$ man qsub
       -V     Available for qsub, qsh, qrsh with command and qalter.

              Specifies that all environment variables active within the qsub utility be exported to  the  context  of  the
              job.

              All  environment  variables  specified  with  -v,  -V  or the DISPLAY variable provided with -display will be
              exported to the defined JSV instances only optionally when this is requested explicitly during the  job  sub‐
              mission verification.  (see -jsv option above or find more information concerning JSV in jsv(1))
```
My guess is that you have not exported `LD_LIBRARY_PATH` in your shell before starting Falcon.

**Comment by ascendo** [comment]
With code hack i add it to code but it doesnt work.

---
Won Cheol Yim

Postdoctoral Researcher

University of Nevada Reno




On Wed, Apr 12, 2017 at 10:24 AM -0700, "Christopher Dunn" <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks fine. I suggested looking for the actual qsub call, to see what flags are actually used. You should see -V:

$ man qsub
       -V     Available for qsub, qsh, qrsh with command and qalter.

              Specifies that all environment variables active within the qsub utility be exported to  the  context  of  the
              job.

              All  environment  variables  specified  with  -v,  -V  or the DISPLAY variable provided with -display will be
              exported to the defined JSV instances only optionally when this is requested explicitly during the  job  sub‐
              mission verification.  (see -jsv option above or find more information concerning JSV in jsv(1))


My guess is that you have not exported LD_LIBRARY_PATH in your shell before starting Falcon.
