### ISSUE TITLE
IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/FALCON_unzip#9]
fc_fetch_reads.py opens an output read file for each input contig. In case the assembly contains more than 1024 contigs a default Debian system throws "IOError: [Errno 24] Too many open files" because ulimit -n is exceeded. Most standard user are not able to change this limit. Either iterate over contigs and through reads multiple times or do it in batches of 1024 contigs.

**Comment by flowers9** [comment]
There seems to be a simple patch for this.  It'll probably slow it down a bit, but you just close the file after you write to it and reopen for appending the next time you want to write to it.

--- fetch_reads.py	2016-07-27 21:24:59.840646000 -0500
+++ fetch_reads.py	2016-07-28 09:20:50.154117000 -0500
@@ -101,15 +101,13 @@
 
                 if ctg_id not in read_out_files:
                     read_out = open( os.path.join( out_dir, "%s_reads.fa" % ctg_id), "w" )
-                    read_out_files[ctg_id] = read_out
+                    read_out_files[ctg_id] = 1
                 else:
-                    read_out = read_out_files[ctg_id]
+                    read_out = open( os.path.join( out_dir, "%s_reads.fa" % ctg_id), "a" )
 
                 print >>read_out, ">"+rid
                 print >>read_out, r.sequence
-
-    for read_out in read_out_files.values():
-        read_out.close()
+                read_out.close()
 
 def parse_args(argv):
     parser = argparse.ArgumentParser(description='using the read to contig mapping data to partition the reads grouped by contigs')

**Comment by pb-cdunn** [comment]
Yeah, could be super slow.

**Comment by flowers9** [comment]
Well, my curent run had maybe 25gb in >5k files, and it actually finished (that part) in a reasonable amount of time.  Might be worth trying, honestly.

**Comment by pb-cdunn** [comment]
Good point.

It's in our Backlog, probably for next week. Maybe you should run with your patch until then? I've pushed your patch to a branch in **FALCON**, `fetch-reads-too-many-files`.

I'm concerned that by totally subverting buffering, we could have an adverse impact on the network for some filesystems, which could adversely impact *other people's runtime*. See my point? A proper solution is not very hard, so I'd rather not spend time investigating the impact of the simple one.

* https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/mains/fetch_reads.py

**Comment by pb-cdunn** [comment]
Ok. We're using the solution provided and tested by @flowers9 for now. (Thanks! If it were a pull-request instead of a pasted snippet, it would even have your name on it.)

If it becomes a bottleneck (for large fasta with fewer than 1024 contigs), we'll look for something else.
