### ISSUE TITLE
Falcon Unzip Concurrents are not working

### ISSUE THREAD

**Issue by AfterRain** [PacificBiosciences/FALCON_unzip#90]
Dear Developer,

I am using SGE and run Falcon-Unzip.
However, every time It is using only 8 concurrent jobs.

unzip cfg files are like below, 

[Unzip]
input_fofn= input.fofn
input_bam_fofn= input_bam.fofn

smrt_bin=/shared2/smrtlink/install/smrtlink-release_5.0.1.9585/bundles/smrttools/smrtcmds/bin

jobqueue = bigmem
sge_phasing= -pe smp 8 -q %(jobqueue)s
sge_quiver= -pe smp 16 -q %(jobqueue)s
sge_track_reads= -pe smp 8 -q %(jobqueue)s
sge_blasr_aln=  -pe smp 8 -q %(jobqueue)s
sge_hasm=  -pe smp 8 -q %(jobqueue)s
unzip_concurrent_jobs = 120
quiver_concurrent_jobs = 60

I ran it with this command "fc_unzip.py fc_unzip.cfg"
However, it doesn't work It looks always try to run with default queue and 8 concurrent.

Do you have any idea how I can increase unzip_concurrent setting?

Thank you,

**Comment by cschin** [comment]
Do you know if you system has a queue called "bigmem"?

**Comment by AfterRain** [comment]
@cschin 

Thank you fo your answer!

Yes, I have bigmem queue I made one script run_example.sh which has configure programs and called "fc_unzip.py fc_unzip.cfg" in that script.

And I run that script just using qsub run_example.sh

It is coming like below,

job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
      5 0.50500 run_exampl smrtanalysis r     08/31/2017 13:43:04 all.q@master                       1
      6 0.60500 P1a25507e4 smrtanalysis r     08/31/2017 13:43:19 default@master                     8

**Comment by AfterRain** [comment]
after this It is supposed to have multiple jobs processing, but It is coming only 8 * 8 jobs are in the queue with default queue. and when I checked log, It is showing concurrent = 8.

**Comment by AfterRain** [comment]
@cschin 

It looks working fine now, 
I just added below two line in the unzip.cfg file. 
I am not so sure It is directly related but I just comment for information. 

unzip_blasr_concurrent_jobs = 120
unzip_phasing_concurrent_jobs = 120

Sincerely,
Seho Choi.
