### ISSUE TITLE
unzip (installed on 20170823) failed at the task 0-phasing/012822F/blasr/task.json

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/FALCON_unzip#93]
Under the directory 3-unzip/reads/, there is a file called '012822F_ref.fa'. But there isn't the corresponding read file '012822F_reads.fa'. And it caused a task's (0-phasing/012822F/blasr/task.json) failure. It needs this read file.

I don't know how to generate this file manually. Can you tell me ?

**Comment by gconcepcion** [comment]
If one reference is absent, it implies that the read tracking step didn't finish properly. There may also be other references missing. 

You can try re-running the read fetching step in track_reads.sh to ensure you've fetched all raw reads.
track_reads.sh
```
$ cat 3-unzip/reads/track_reads.sh
set -vex
trap 'touch /lustre/hpcprod/gconcepcion/170814Hemichordate/3-unzip/reads/track_reads_done.exit' EXIT
hostname
date
cd ../..
#python -m falcon_kit.mains.get_read_ctg_map
#python -m falcon_kit.mains.rr_ctg_track
#python -m falcon_kit.mains.pr_ctg_track
#mkdir -p 3-unzip/reads/
python -m falcon_kit.mains.fetch_reads
cd /lustre/hpcprod/gconcepcion/170814Hemichordate/3-unzip/reads
date
touch /lustre/hpcprod/gconcepcion/170814Hemichordate/3-unzip/reads/track_reads_done
```

Comment out the first three python steps, and try re-running the final `python -m falcon_kit.mains.fetch_reads` step by itself.

**Comment by nottwy** [comment]
Thanks for your reply!
I have read your code and found a problem.
I have a contig whose name is '012822F'. I scan the file 'rawread_ids' and 'pread_ids' to find the pattern /012822F 0/. Because in your code 'fetch_reads.py' it requires 'int(row[3]) == 0'.
So what does the value of row[3] mean?

And in my case, I have modified your code to make sure some values of the contig '012822F' satisfying your requirement of output, including:
1. The ctg_id_hits value of 012822F is: 5
2. 012822F is in the all_ctg_ids

So do you have any suggestion about where there would be a problem?
Thanks!

**Comment by nottwy** [comment]
I have found the reason.
There are some errors in your function 'pid_to_oid(pid)'. It caused different preads linked to the same subreads. And the latter one will overwrite the former one. So the subreads of contig 012822F are linked to other contigs and can't be outputed. I'm sure it's a bug. How do you think of this problem?

**Comment by cschin** [comment]
@nottwy Due to the error rate and repeat genome content, it is possible that a subread can be used in correcting multiple preads. However, each pid read can be only trace to single subread (or one of the subreads from the ZMW, persumablly the all subreads from the same ZMW are from the same molecule).  In your case, it is like not there is no unique track from a pid to a subread. But there are some better and worse error corrected reads, and all subreads are eventually be recurited by the better one.

**Comment by nottwy** [comment]
Let's start from a simple point.
Now I just want to make unzip work properly. But because the file '012822F_reads.fa' can't be created due to the reason I said above, unzip always reported an error and can't proceed.
How can I solve this problem?
-----------------------------------------------------------------------------------------
I have discover the reason completely. It's like this:
1. we find there are enough subreads for contig 012822F, so the contig 012822F is included in.
2. unzip try to output the corresponding subreads of this contig, it finds and stores the relationship between subreads and this contig.
3. because these subreads are also linked to other contigs, so the relationship between these subreads and the contig 012822F lost.
4. the file  012822F_reads.fa can't be generated;
5. unzip reported an error and stoped.
------------------------------------------------------------------------------------------
Wait for your reply! @cschin ,also @gconcepcion

**Comment by cschin** [comment]
Again, please ask @PacBio for how they want to "officially" (if there is such thing) handle this for you. On the other, the design was the code will look for a list to see which config should be processed. You can remove the problematic config from the list.  There is a way to hack through it as you have the source code. I simply have no resource to test any suggestion I made now.

**Comment by nottwy** [comment]
OK. Let's wait for @gconcepcion 's reply.

**Comment by gconcepcion** [comment]
Hi nottwy, 

It sounds like you have a good grasp on the problem, please feel free to submit a pull request and we can integrate a fix into the code. In the meantime, @cschin has provided a valid work around, simply remove that contig from the file 3-unzip/reads/ctg_list file and re-run the unzip pipeline. The offending contig should be ignored and you will be able to proceed with the pipeline.

**Comment by nottwy** [comment]
@gconcepcion ,
Thanks for @cschin 's advice.I also find this way but put it aside before because I think it's not a way to solve this problem. There should be other choice but it may take some time to find it. I'm trying but haven't found it yet. I'm still thinking of this problem. If I have any progress or any interesing ideas, I will send them to u and ask for your opinions if you leave me your contacts (or send them to me: nottwya@gmail.com). Or I'll paste them here. Maybe you can't notice my issue in time because I know u receive lots of issues notification every day.

**Comment by nottwy** [comment]
I find that there may exist an oid-rid match error. @gconcepcion 
In this file (file A) '2-asm-falcon/read_maps/get_ctg_read_map', it's the relationship the unzip uses to determine the match between oid and rid. And in (file B) '2-asm-falcon/read_maps/dump_rawread_ids/rawread_ids', it contains names of all subreads which are dumped from the database.
The problem is, for example, the oid of the subread at the 3th row of the file B should be 3. (We get this conclusion from the las file. The first column and the second column of the las file are oid. Is it correct? And it starts from 1.) But in the file A, it became 2. And all oids of the subreads in the file A are 1 smaller than the the oids of the corresponding subreads.

**Comment by nottwy** [comment]
@cschin @gconcepcion ,
The observation I presented above is based on the unzip from this link:
https://downloads.pacbcloud.com/public/falcon/falcon-2017.06.28-18.01-py2.7-ucs4.tar.gz
And I install my falcon and falcon-unzip with this script:
http://pb-falcon.readthedocs.io/en/latest/_downloads/install_unzip.sh
Hope this can help u locate the bug of the code.

**Comment by iggyB** [comment]
Hi,

Any progress? Any ideas? 

Bumped into similar issue. 22 contigs have no corresponding reads.fa

**Comment by nottwy** [comment]
Finally, I found that:
LA4Falcon and LAshow works slightly differently.
The id of LA4Falcon starts from 0 and LAshow starts from 1.
